{% set name = "baybe" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/baybe-{{ version }}.tar.gz
  sha256: b700cc8b586a4c425f3a8f2641a35f2ec224b96e9e14182d3c10f0aaea58167f
  patches:
    - pyproject.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<3.13
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.10,<3.13
    - attrs >=22.2.0
    - botorch >=0.9.3,<1
    - cattrs >=23.2.0
    - exceptiongroup
    - funcy >=1.17
    - gpytorch >=1.9.1,<2
    - ngboost >=0.3.12,<1
    - numpy >=1.24.1,<2
    - pandas >=1.4.2
    - protobuf >=3.20.3
    - scikit-learn >=1.1.1,<2
    - scikit-learn-extra >=0.3.0,<1
    - scipy >=1.10.1,<2
    - setuptools-scm >=7.1.0
    - pytorch >=1.13.1,<3
    - typing-extensions >=4.7.0
    - opentelemetry-sdk >=1.16.0
    - opentelemetry-propagator-aws-xray >=1.0.0
    - opentelemetry-exporter-otlp >=1.16.0
    - opentelemetry-sdk-extension-aws >=2.0.0

test:
  imports:
    - baybe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://emdgroup.github.io/baybe/
  summary: A Bayesian Back End for Design of Experiments
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
